DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  - BASH_SHELLCHECK
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_DEVSKIM
  # TYPESCRIPT_STANDARD NOT BEEN UPDATED SINCE 2022
  - TYPESCRIPT_STANDARD

SHOW_ELAPSED_TIME: true
SARIF_REPORTER: true
GITHUB_STATUS_REPORTER: true
APPLY_FIXES: all

# Disable unnecessary stuff
FILEIO_REPORTER: false
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
